spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: example
      database: demo
      port: 27017
      host: localhost
  redis:
    password: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81